[versions]
kotlin = "1.6.10"
compose = "1.1.1"
coroutines = "1.6.3"
koin = "3.2.0"
junit4 = "4.13"
junit5 = "5.8.2"
mockk = "1.12.4"
kotest = "5.3.2"
dependency-updates = "0.42.0"
ktlint = "0.46.1"
spotless = "6.8.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
dependency-updates = { id = "com.github.ben-manes.versions", version.ref = "dependency-updates" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
compose-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose" }
compose-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "compose" }
compose-test-junit4 = { module = "org.jetbrains.compose.ui:ui-test-junit4", version.ref = "compose" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-junit5 = { module = "io.insert-koin:koin-test-junit5", version.ref = "koin" }
junit5 = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
